name: Lambda Release

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag v4.2.2
      with:
        fetch-depth: 0

    - name: test
      run: echo ${GITHUB_REF_NAME}

    - name: Create release tags for Lambda and K8s Init Containers
      run: |
        echo v${GITHUB_REF_NAME}
        
        RELEASE_TITLE="New Relic Ruby Agent v${GITHUB_REF_NAME}.0"
        RELEASE_TAG="v${GITHUB_REF_NAME}.0_ruby"
        RELEASE_NOTES="Automated release for [Ruby Agent v${GITHUB_REF_NAME}](https://github.com/newrelic/newrelic-ruby-agent/releases/tag/v${GITHUB_REF_NAME})"       
      env:
        GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
